name: get-ad-list

# 定义触发器，定期执行此工作流
on:
  schedule:
    - cron: '0 0 */15 * *'  # 每天午夜运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 拉取远程文件
    - name: Download conf file
      run: |
        curl -o my_ad.txt https://raw.githubusercontent.com/Teacher-c/MosDNS_AD/refs/heads/main/MosDNS_Block.txt
        curl -o Advertising_tmp.txt https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/Advertising/Advertising.txt
        curl -o AdvertisingMiTV.txt https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/AdvertisingMiTV/AdvertisingMiTV.txt
        curl -o apple_simple.txt https://raw.githubusercontent.com/Teacher-c/clash/refs/heads/main/apple_domain_simple.conf
        curl -o MyDirect.txt https://raw.githubusercontent.com/Teacher-c/clash/refs/heads/main/MyDirect.conf
    
    # 使用 sed 命令修改文件
    - name: Modify file
      run: |
        sed -i '/^[!#]/d; /^\s*$/d; s/||//g; s/\^//g' Advertising_tmp.txt my_ad.txt AdvertisingMiTV.txt
        sed -i 's/server=\/\|\/223\.5\.5\.5//g' MyDirect.txt apple_simple.txt
        cat my_ad.txt AdvertisingMiTV.txt Advertising_tmp.txt >> Advertising.txt
        cat MyDirect.txt >> whitelist.txt
        awk '!seen[$0]++' Advertising.txt > tmp && mv tmp Advertising.txt
        awk '!seen[$0]++' whitelist.txt > tmp1 && mv tmp1 whitelist.txt
        rm -rf my_ad.txt Advertising_tmp.txt apple_simple.txt MyDirect.txt
        
      # 提交修改并推送到仓库
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update file"
        git push
