name: get-ad-list

# 定义触发器，定期执行此工作流on:
  schedule:
    - cron: "0 0 * * 1"  # 每周一 00:00 UTC 执行
  workflow_dispatch:     # 也允许手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 拉取远程文件
    - name: Download conf file
      run: |
        curl -o Advertising_tmp.txt https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/Advertising/Advertising.txt
        curl -o AdvertisingMiTV.txt https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/AdvertisingMiTV/AdvertisingMiTV.txt
        curl -o apple_simple.txt https://raw.githubusercontent.com/mphin/proxy_tools/refs/heads/main/rules/Apple.list
    
    # 使用 sed 命令修改文件
    - name: Modify file
      run: |
        cp my_ad.txt my_ad_tmp.txt
        sed -i '/^[!#]/d; /^\s*$/d; s/||//g; s/\^//g' Advertising_tmp.txt my_ad_tmp.txt AdvertisingMiTV.txt
        sed -i '/^\s*$/d; /^[#]/d; /^IP-CIDR/d' apple_simple.txt
        awk -F',' '{print $2}' apple_simple.txt >> tmp && mv tmp apple_simple.txt
        rm -rf Advertising.txt 
        cat my_ad_tmp.txt AdvertisingMiTV.txt Advertising_tmp.txt >> Advertising.txt
        rm -rf my_ad_tmp.txt Advertising_tmp.txt AdvertisingMiTV.txt
        
      # 提交修改并推送到仓库
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update file"
        git push
